tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "primary-fixed": "#c1ecd4",
                "on-tertiary-container": "#7eafb1",
                "surface-container-high": "#e7e8e9",
                "tertiary-container": "#0b4345",
                "on-primary": "#ffffff",
                "on-secondary": "#ffffff",
                "primary-fixed-dim": "#a5d0b9",
                "tertiary": "#002c2d",
                "primary": "#012d1d",
                "surface-container": "#edeeef",
                "surface-container-low": "#f3f4f5",
                "on-primary-fixed": "#002114",
                "secondary-fixed-dim": "#95d4b3",
                "secondary-container": "#aeeecb",
                "on-surface-variant": "#414844",
                "on-surface": "#191c1d",
                "on-primary-container": "#86af99",
                "on-secondary-container": "#316e52",
                "background": "#f8f9fa",
                "surface-dim": "#d9dadb",
                "outline": "#717973",
                "inverse-on-surface": "#f0f1f2",
                "on-tertiary-fixed-variant": "#1a4e50",
                "surface-container-highest": "#e1e3e4",
                "on-tertiary": "#ffffff",
                "tertiary-fixed-dim": "#9ecfd1",
                "surface-bright": "#f8f9fa",
                "secondary-fixed": "#b1f0ce",
                "secondary": "#2c694e",
                "surface": "#f8f9fa",
                "surface-container-lowest": "#ffffff",
                "error": "#ba1a1a",
                "surface-tint": "#3f6653",
                "on-error-container": "#93000a",
                "surface-variant": "#e1e3e4",
                "tertiary-fixed": "#b9ecee",
                "inverse-surface": "#2e3132",
                "on-primary-fixed-variant": "#274e3d",
                "on-tertiary-fixed": "#002021",
                "on-secondary-fixed": "#002114",
                "on-background": "#191c1d",
                "primary-container": "#1b4332",
                "outline-variant": "#c1c8c2",
                "error-container": "#ffdad6",
                "inverse-primary": "#a5d0b9",
                "on-error": "#ffffff",
                "on-secondary-fixed-variant": "#0e5138"
            },
            "borderRadius": {
                "DEFAULT": "1rem",
                "lg": "2rem",
                "xl": "3rem",
                "full": "9999px"
            },
            "spacing": {
                "stack-lg": "2rem",
                "stack-sm": "0.5rem",
                "container-max": "1280px",
                "margin-desktop": "2.5rem",
                "margin-mobile": "1rem",
                "stack-md": "1rem",
                "gutter": "1.5rem"
            },
            "fontFamily": {
                "body-lg": ["Plus Jakarta Sans"],
                "headline-lg-mobile": ["Plus Jakarta Sans"],
                "label-sm": ["Plus Jakarta Sans"],
                "headline-xl": ["Plus Jakarta Sans"],
                "headline-lg": ["Plus Jakarta Sans"],
                "headline-md": ["Plus Jakarta Sans"],
                "body-md": ["Plus Jakarta Sans"],
                "label-lg": ["Plus Jakarta Sans"]
            },
            "fontSize": {
                "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
                "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "700"}],
                "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "600"}],
                "headline-xl": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "800"}],
                "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700"}],
                "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "700"}],
                "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
                "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600"}]
            }
        },
    },
}
